language: r
cache: packages
before_install: Rscript -e 'source("https://install-github.me/r-lib/remotes")'
r_packages:
  - EML
  - stringr
  - stringi
  - reader
  - readr
  - xml2
  - httr
  - knitr
  - rmarkdown
  - methods
  - covr
  - EDIutils
r_github_packages:
  - EDIorg/EDIutils
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
